config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  get '/todos', to: 'todos#index'

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to root_url
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      redirect_to root_url
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    Todo.find(params[:id]).destroy
    redirect_to root_url, status: :see_other
  end

  private

    def todo_params
      params.require(:todo).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
  <%= form_with(model: @todo) do |f|  %>
    <%= f.text_field :title %>
    <%= f.submit "保存する" %>
  <% end %>

app/views/todos/edit.html.erb
<div class="container">
  <h1>タスクの編集</h1>
  <%= render 'form' %>
</div>

app/views/todos/index.html.erb
<div class="container">
  <h1>Todo List</h1>

  <%= link_to "タスクを追加する", new_todo_path, class: 'new-task' %>

  <table>
    <thead>
      <tr>
        <th>タスク</th>
        <th>アクション</th>
      </tr>
    </thead>
    <tbody>

      <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.title %></td>
          <td>
            <%= link_to "編集", edit_todo_path(todo), class: 'edit' %>
            <%= link_to "削除", todo, class: 'delete', data: { "turbo-method": :delete, turbo_confirm: "本当に削除していいですか?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/todos/new.html.erb
<div class="container">
  <h1>タスクの追加</h1>
  <%= render 'form' %>
</div>